---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Download requirement pip sources
  shell: >
    yes i | pip install --timeout {{ repo_build_timeout }} \
                        --download {{ repo_build_output }} \
                        --no-binary :all: \
                        --constraint {{ repo_build_release_path }}/{{ repo_build_release_tag }}/requirements_constraints.txt \
                        {% if repo_build_pip_default_index is defined %}
                        --index-url {{ repo_build_pip_default_index }} \
                        --trusted-host {{ repo_build_pip_default_index | netloc_no_port }} \
                        {% endif -%}
                        {% if repo_build_pip_extra_index is defined %}
                        --extra-index-url {{ repo_build_pip_extra_index }} \
                        --trusted-host {{ repo_build_pip_extra_index | netloc_no_port }} \
                        {% endif -%}
                        {% if repo_build_pip_extra_indexes is defined %}
                        --extra-index-url {{ repo_build_pip_extra_indexes | join(' --extra-index-url ') }} \
                        --trusted-host {{ repo_build_pip_extra_indexes | map('netloc_no_port') | join(' --trusted-host ') }} \
                        {% endif -%}
                        --log /var/log/repo/repo_builder.log \
                        --requirement {{ repo_build_release_path }}/{{ repo_build_release_tag }}/requirements.txt
  when: repo_build_store_pip_sources | bool
  tags:
    - repo-pip-download
 
- name: inserted by bhujay for upgrading packaing to 16.8 before wheel is build 
  pip:
    name: "{{ items }}"
    state: present
  with_items: 
    - packaging==16.8

- name: Create OpenStack-Ansible requirement wheels
  shell: >
    pip wheel --timeout {{ repo_build_timeout }}
    --wheel-dir {{ repo_build_output }}
    --find-links {{ repo_build_global_links_path }}
    --find-links {{ repo_build_output }}
    --constraint {{ repo_build_release_path }}/{{ repo_build_release_tag }}/requirements_constraints.txt
    {% if repo_build_pip_no_binary is defined %}--no-binary {{ repo_build_pip_no_binary | join(' --no-binary ') }}{% endif %}
    {% if repo_build_pip_default_index is defined %}--index-url {{ repo_build_pip_default_index }}
    --trusted-host {{ repo_build_pip_default_index | netloc_no_port }}{% endif %}
    {% if repo_build_pip_extra_index is defined %}--extra-index-url {{ repo_build_pip_extra_index }}
    --trusted-host {{ repo_build_pip_extra_index | netloc_no_port }}{% endif %}
    {% if repo_build_pip_extra_indexes is defined %}--extra-index-url {{ repo_build_pip_extra_indexes | join(' --extra-index-url ') }}
    --trusted-host {{ repo_build_pip_extra_indexes | map('netloc_no_port') | join(' --trusted-host ') }}{% endif %}
    --build {{ repo_build_dir }}
    --log /var/log/repo/repo_builder.log
    --requirement {{ repo_build_release_path }}/{{ repo_build_release_tag }}/requirements.txt
    {{ pip_install_options }}
  tags:
    - repo-build-local-requirement-wheels
    - repo-build-openstack-ansible-requirement-wheels
    
- name: inserted by bhujay for reverting back  packaing to 16.7 after  wheel is build 
  pip:
    name: "{{ items }}"
    state: present
  with_items: 
    - packaging==16.7
  
  
  