---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create a service
- name: Ensure glance service
  keystone:
    command: "ensure_service"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    description: "{{ glance_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 2

# Create an admin user
- name: Ensure glance user
  keystone:
    command: "ensure_user"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ glance_service_user_name }}"
    tenant_name: "{{ glance_service_project_name }}"
    password: "{{ glance_service_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  when: not glance_service_in_ldap | bool
  until: add_service|success
  retries: 5
  delay: 10

# Add a role to the user
- name: Ensure glance user to admin role
  keystone:
    command: "ensure_user_role"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    user_name: "{{ glance_service_user_name }}"
    tenant_name: "{{ glance_service_project_name }}"
    role_name: "{{ glance_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  when: not glance_service_in_ldap | bool
  until: add_service|success
  retries: 5
  delay: 10

# Create an endpoint
- name: Ensure glance endpoint
  keystone:
    command: "ensure_endpoint"
    endpoint: "{{ keystone_service_adminurl }}"
    login_user: "{{ keystone_admin_user_name }}"
    login_password: "{{ keystone_auth_admin_password }}"
    login_project_name: "{{ keystone_admin_tenant_name }}"
    region_name: "{{ glance_service_region }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ glance_service_publicurl }}"
        interface: "public"
      - url: "{{ glance_service_internalurl }}"
        interface: "internal"
      - url: "{{ glance_service_adminurl }}"
        interface: "admin"
  register: add_service
  until: add_service|success
  retries: 5
  delay: 10
